version: '3.8'

services:
  redis:
    image: 'redislabs/rejson:latest'
    command: redis-server --requirepass password
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'
volumes:
  redisdata:
